package com.bezgrebelny.imgurgalleryapp.core.api.model

import com.google.gson.annotations.SerializedName

data class GalleryImage(
    @SerializedName("id") val id: String?,
    @SerializedName("title") val title: String?,
    @SerializedName("description") val description: Any?,
    @SerializedName("datetime") val datetime: Int?,
    @SerializedName("type") val type: String?,
    @SerializedName("animated") val animated: Boolean?,
    @SerializedName("width") val width: Int?,
    @SerializedName("height") val height: Int?,
    @SerializedName("size") val size: Int?,
    @SerializedName("views") val views: Int?,
    @SerializedName("bandwidth") val bandwidth: Long?,
    @SerializedName("vote") val vote: Any?,
    @SerializedName("favorite") val favorite: Boolean?,
    @SerializedName("nsfw") val nsfw: Boolean?,
    @SerializedName("section") val section: String?,
    @SerializedName("account_url") val accountUrl: String?,
    @SerializedName("account_id") val accountId: Int?,
    @SerializedName("is_ad") val isAd: Boolean?,
    @SerializedName("in_most_viral") val inMostViral: Boolean?,
    @SerializedName("has_sound") val hasSound: Boolean?,
    @SerializedName("tags") val tags: List<Tag>?,
    @SerializedName("ad_type") val adType: Int?,
    @SerializedName("ad_url") val adUrl: String?,
    @SerializedName("edited") val edited: Int?,
    @SerializedName("in_gallery") val inGallery: Boolean?,
    @SerializedName("topic") val topic: String?,
    @SerializedName("topic_id") val topicId: Int?,
    @SerializedName("link") val link: String?,
    @SerializedName("ad_config") val adConfig: AdConfig?,
    @SerializedName("comment_count") val commentCount: Int?,
    @SerializedName("favorite_count") val favoriteCount: Int?,
    @SerializedName("ups") val ups: Int?,
    @SerializedName("downs") val downs: Int?,
    @SerializedName("points") val points: Int?,
    @SerializedName("score") val score: Int?,
    @SerializedName("is_album") val isAlbum: Boolean?
)